version = 1

[device.cf2_flow2_lighthouse]
radio = "radio://0/50/2M/E7E7E71706"
decks = ["bcFlow2", "bcLighthouse4"]
bootloader_radio = "radio://0/0/2M/B19CF77F05?safelink=0"

[device.cf2_flow2]
radio = "radio://0/50/2M/E7E7E71705"
decks = ["bcFlow2"]
bootloader_radio = "radio://0/0/2M/B16298A8A3?safelink=0"

[device.cf2_flow2_multiranger]
radio = "radio://0/50/2M/E7E7E71704"
decks = ["bcFlow2", "bcMultiranger"]
bootloader_radio = "radio://0/0/2M/B1CEE678C5?safelink=0"

# [device.cf2_usddeck]
# radio = "radio://0/50/2M/E7E7E71703"
# decks = ["bcUSD"]
# bootloader_radio = "radio://0/0/2M/B164C8AC96?safelink=0"

# [device.cf2_lighthouse]
# radio = "radio://0/50/2M/E7E7E71702"
# bootloader_radio = "radio://0/0/2M/B1F519F77B?safelink=0"
# decks = ["bcLighthouse4"]

[device.cf2_stock]
radio = "radio://0/50/2M/E7E7E71701"
bootloader_radio = "radio://0/0/2M/B177790F3A?safelink=0"
